name: Delete Build Artifact
description: Delete a build artifact that was previously uploaded in the workflow by the upload-artifact action
author: Giao Ho
inputs:
  owner:
    description: The name of the owner of the repo, this is the repository that artifacts will be deleted from. Default is current owner.
    required: false
  repo:
    description: The name of the repository, this is the repository that artifacts will be deleted from. Default is current repository.
    required: false
  run-id:
    description: 'The id of the workflow run where the desired delete artifact was uploaded from.
      If github-token is specified, this is the run that artifacts will be deleted from.'
    required: false
  token:
    description: 'The GitHub token used to authenticate with the GitHub API.
      This is required when deleting artifacts from a different repository or from a different workflow run.
      If this is not specified, the action will attempt to delete artifacts from the current repository and the current workflow run.'
    required: false
  latest:
    description: Filter the workflow run's artifacts to the latest by name In the case of reruns, this can be useful to avoid duplicates
    required: false
  name:
    description: The name of the artifact to delete, multiple names can be supplied on new lines.
    required: false
  pattern:
    description: A glob pattern matching the artifacts that should be deleted. Ignored if name is specified.
    required: false
runs:
  using: node20
  main: action/index.js
branding:
  icon: trash-2
  color: red
